### ISSUE TITLE
nuxt run generate 报错

### ISSUE THREAD

**Issue by ghost** [FE-Driver/vue-beauty#236]
WARNING in ./node_modules/css-loader?{"minimize":true,"importLoaders":1,"sourceMap":false,"alias":{"/static":"E://project//melon//trunk//frontend//online//manager//static","/assets":"E:
(Emitted value instead of an instance of Error) autoprefixer: E:\project\melon\trunk\frontend\online\manager\node_modules\vue-beauty\package\style\vue-beauty.min.css:9619:3: Second Auto
 @ ./node_modules/vue-beauty/package/style/vue-beauty.min.css 4:14-133
 @ ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":false,"presets":["E://project//melon//trunk//frontend//online//manager//node_modules//babel-preset-vue-app//dist//in
 @ ./.nuxt/App.vue
 @ ./.nuxt/index.js
 @ ./.nuxt/server.js
  nuxt:generate Destination folder cleaned +0ms
  nuxt:generate Static & build files copied +172ms
Generating routes
  nuxt:render Rendering url / +0ms
[vue-router] Failed to resolve async component default: ReferenceError: window is not defined
[vue-router] uncaught error during route navigation:
ReferenceError: window is not defined
    at Object.<anonymous> (E:\project\melon\trunk\frontend\online\manager\node_modules\vue-beauty\package\vue-beauty.min.js:1:329244)
    at m (E:\project\melon\trunk\frontend\online\manager\node_modules\vue-beauty\package\vue-beauty.min.js:1:326011)
    at Object.<anonymous> (E:\project\melon\trunk\frontend\online\manager\node_modules\vue-beauty\package\vue-beauty.min.js:1:326043)
    at e (E:\project\melon\trunk\frontend\online\manager\node_modules\vue-beauty\package\vue-beauty.min.js:1:382)
    at Object.<anonymous> (E:\project\melon\trunk\frontend\online\manager\node_modules\vue-beauty\package\vue-beauty.min.js:1:58872)
    at e (E:\project\melon\trunk\frontend\online\manager\node_modules\vue-beauty\package\vue-beauty.min.js:1:382)
    at t.exports.t (E:\project\melon\trunk\frontend\online\manager\node_modules\vue-beauty\package\vue-beauty.min.js:1:748)
    at E:\project\melon\trunk\frontend\online\manager\node_modules\vue-beauty\package\vue-beauty.min.js:1:759
    at n (E:\project\melon\trunk\frontend\online\manager\node_modules\vue-beauty\package\vue-beauty.min.js:1:81)
    at Object.<anonymous> (E:\project\melon\trunk\frontend\online\manager\node_modules\vue-beauty\package\vue-beauty.min.js:1:258)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
{ Error: ENOENT: no such file or directory, lstat 'E:\project\melon\trunk\frontend\online\manager\dist\index.html'

**Comment by yuu2lee4** [comment]
不兼容ssr
