### ISSUE TITLE
npm run build 出错

### ISSUE THREAD

**Issue by zhuewizz** [FE-Driver/vue-beauty#42]
ERROR in ./~/.npminstall/vue-html-loader/1.2.3/vue-html-loader!./~/.npminstall/vue-loader/8.5.3/vue-loader/lib/selector.js?type=template&index=0!./components/timePicker/timePickerOption.vue
Module build failed: Error: Parse Error: <10?0:''}}{{$index}}</li>
                    </ul>
                </div>
                <div class="ant-time-picker-panel-select">
                    <ul @mouseover="createSelection($els.timePickerPanel, 3, 5)">
                        <li v-for="($index) in 60" @click="timePicker('M', $event)" v-if="showLi($index, 'M')" :class="selectedCls(M, $index, 'M')">{{$index<10?0:''}}{{$index}}</li>
                    </ul>
                </div>
                <div class="ant-time-picker-panel-select" v-if="hasSeconds">
                    <ul @mouseover="createSelection($els.timePickerPanel, 6, 8)">
                        <li v-for="($index) in 60" @click="timePicker('S', $event)" v-if="showLi($index, 'S')" :class="selectedCls(S, $index, 'S')">{{$index<10?0:''}}{{$index}}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
    at new HTMLParser (G:\vue-beauty\node_modules\.npminstall\html-minifier\2.1.7\html-minifier\src\htmlparser.js:236:13)
    at minify (G:\vue-beauty\node_modules\.npminstall\html-minifier\2.1.7\html-minifier\src\htmlminifier.js:945:3)
    at Object.exports.minify (G:\vue-beauty\node_modules\.npminstall\html-minifier\2.1.7\html-minifier\src\htmlminifier.js:1294:10)
    at Object.module.exports (G:\vue-beauty\node_modules\.npminstall\vue-html-loader\1.2.3\vue-html-loader\index.js:85:26)
 @ ./components/timePicker/timePickerOption.vue 3:19-169

**Comment by yuu2lee4** [comment]
切到develop分支、。。。。
